---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: prestashop
  namespace: prestashop
  labels:
    env: home
spec:
  storageClassName: longhorn
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
