mysql:
  volumeSpec:
    pvc:
      resources:
        requests:
          storage: 15Gi
  size: 1
  resources:
    requests:
      memory: 512Mi
      cpu: 0.1
    limits:
      memory: 2Gi
      cpu: 2

backup:
  enabled: false

proxy:
  haproxy:
    size: 1
    resources:
      requests:
        memory: 256Mi
        cpu: 0.1
      limits:
        memory: 512Mi
        cpu: 1
