---
apiVersion: v1
kind: Secret
metadata:
  name: auth-kubewall
  namespace: kubewall
  labels:
    env: home
    htpasswd:  kubewall
type: Opaque
data:
  auth: YWRtaW46JGFwcjEkMGh1NnEyNXQkVmZKcVpXODFaUXUvWXp2SFlYbnZOMQ==
