---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: default
  namespace: metallb-system
  labels:
    app.kubernetes.io/env: home
spec:
  addresses:
  - 192.168.1.120-192.168.1.130
  autoAssign: true
