---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubewall
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: hostfab-dev
  sources:
  - repoURL: git@github.com:bedrockmasterbg/hostfab-dev.git
    targetRevision: main
    ref: values
  - repoURL: oci://ghcr.io/kubewall/charts/kubewall
    targetRevision: 0.0.14
    chart: kubewall
    helm:
      skipCrds: false
      valueFiles:
      - '$values/helm/kubewall/values.yaml'
  - repoURL: git@github.com:bedrockmasterbg/hostfab-dev.git
    targetRevision: main
    path: manifests/kubewall
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: kubewall
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
