---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgresql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: hostfab-dev
  sources:
  - repoURL: git@github.com:bedrockmasterbg/hostfab-dev.git
    targetRevision: main
    ref: values
  - repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 2.7.0
    chart: pg-operator
  - repoURL: https://percona.github.io/percona-helm-charts/
    targetRevision: 2.7.0
    chart: pg-db
    helm:
      valueFiles:
      - '$values/helm/postgresql/values.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: prestashop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
