---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prestashop
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    env: home
spec:
  project: hostfab-dev
  sources:
  - repoURL: git@github.com:bedrockmasterbg/hostfab-dev.git
    targetRevision: main
    ref: values
  - repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 22.0.5
    chart: prestashop
    helm:
      valueFiles:
      - '$values/helm/prestashop/values.yaml'
  # - repoURL: git@github.com:bedrockmasterbg/hostfab-dev.git
  #   targetRevision: main
  #   path: manifests/prestashop
  #   directory:
  #     recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: prestashop
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - Validate=true
    - PrunePropagationPolicy=foreground
    - PruneLast=true
    - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
